docs_dir: doc
site_dir: build/html
pages:
    - index.md
site_name: Org_Heigl\Ghostscript
site_description: A wrapper to the Ghostscript CLI
repo_url: 'https://github.com/heiglandreas/Org_Heigl_Ghostscript'
copyright: 'Copyright (c) <a href="http://andreas.heigl.org/">Andreas Heigl</a>'
